meta:
    site_title: "沧苑个人博客"
    site_subtitle: "心有多远就能走多远"
    site_language: "zh-cn"
    # absolute_baseurl: http://art.yanping.me
    domain: yxiaodan.info
    author:
        full_name: Cangyuan
        # short_name: ypchen
        # name: ypchen
        email: 1339918746@qq.com

url: http://yxiaodan.info

baseurl: /

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

      
css:
    - css/screen.css


